name: Deploy EC2 using AWS CloudFormation

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'CloudFormation action to perform'
        required: true
        default: 'deploy'
        type: choice
        options:
          - deploy
          - destroy

      StackName:
        description: 'Enter your CloudFormation Stack Name'
        required: true
        default: 'project-stack'
        type: string
      
      VpcID:
        Description: "Enter your VPC ID"
        Default: "vpc-03aa2d44aeeee4e02"
        required: true
        type: string

      SubnetID:
        Description: "Enter your Subnet ID"
        Default: "subnet-08c44f4adae36b232"
        required: true
        type: string

      AmiID:
        Description: "Enter your AMI ID"
        Default: "ami-0ca1796cb5fd02cb8"
        required: true
        type: string

      SecurityGroupID:
        Description: "Enter your Security Group ID"
        Default: "sg-058255f528c7c43bf"
        required: true
        type: string

      InstanceType:
        Description: "Enter your Instance Type"
        Default: "t3.micro"
        required: true
        type: string

      KeyPair:
        Description: "Enter your Key Pair"
        Default: "dnag-kp"
        required: true
        type: string

permissions:
  id-token: write
  contents: read

env:
  TEMPLATE_FILE: ec2-template.yaml

jobs:
  cloudformation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Debug OIDC claims
        run: |
          TOKEN=$(curl -sH "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com" | jq -r '.value')

          echo "$TOKEN" \
            | cut -d. -f2 \
            | base64 -d 2>/dev/null \
            | jq '{sub, aud, repository}'

      - name: Configure AWS credentials from IAM Role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Validate CloudFormation template
        run: |
          aws cloudformation validate-template \
            --template-body file://${{ env.TEMPLATE_FILE }}

      - name: Deploy CloudFormation Stack
        if: ${{ github.event.inputs.action == 'deploy' }}
        run: |
          aws cloudformation deploy \
            --stack-name "${{ github.event.inputs.StackName }}" \
            --template-file "${{ env.TEMPLATE_FILE }}" \
            --parameter-overrides \
              VpcID="${{ github.event.inputs.VpcID }}" \
              SubnetID="${{ github.event.inputs.SubnetID }}" \
              AmiID="${{ github.event.inputs.AmiID }}" \
              SecurityGroupID="${{ github.event.inputs.SecurityGroupID }}" \
              KeyPair="${{ github.event.inputs.KeyPair }}" \
              InstanceType="${{ github.event.inputs.InstanceType }}" \
            --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM

      - name: Delete CloudFormation Stack
        if: ${{ github.event.inputs.action == 'destroy' }}
        run: |
          aws cloudformation delete-stack \
            --stack-name "${{ github.event.inputs.StackName }}"

          echo "Waiting for stack deletion..."

          aws cloudformation wait stack-delete-complete \
            --stack-name "${{ env.STACK_NAME }}"

          echo "CloudFormation stack deleted successfully."