name: Deploy Q16 Quiz using AWS CloudFormatio, destroy

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'CloudFormation action to perform'
        required: true
        default: 'deploy'
        type: choice
        options:
          - deploy
          - destroy

      StackName:
        description: 'Enter your CloudFormation Stack Name'
        required: true
        default: 'project-stack'
        type: string
      
      InstanceType:
        Description: "Enter your Instance Type"
        Default: "t3.micro"
        required: true
        type: choice
        options:
          - t2.micro
          - t3.micro
          - t3.small

      BucketName:
        Description: "Enter your S3 bucket Name"
        Default: "q16-quiz-s3-01-10-2026"
        required: true
        type: string

      LatestAmiId:
        Description: "Enter your Latest AMI ID"
        Default: "/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64"
        required: true
        type: string

permissions:
  id-token: write
  contents: read

env:
  TEMPLATE_FILE: q16-quiz.yaml

jobs:
  cloudformation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Debug OIDC claims
        run: |
          TOKEN=$(curl -sH "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com" | jq -r '.value')

          echo "$TOKEN" \
            | cut -d. -f2 \
            | base64 -d 2>/dev/null \
            | jq '{sub, aud, repository}'

      - name: Configure AWS credentials from IAM Role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Validate CloudFormation template
        run: |
          aws cloudformation validate-template \
            --template-body file://${{ env.TEMPLATE_FILE }}

      - name: Deploy CloudFormation Stack
        if: ${{ github.event.inputs.action == 'deploy' }}
        run: |
          aws cloudformation deploy \
            --stack-name "${{ github.event.inputs.StackName }}" \
            --template-file "${{ env.TEMPLATE_FILE }}" \
            --parameter-overrides \
              InstanceType="${{ github.event.inputs.InstanceType }}" \
              BucketName="${{ github.event.inputs.BucketName }}" \
              LatestAmiId="${{ github.event.inputs.LatestAmiId }}" \
            --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM

      - name: Delete CloudFormation Stack
        if: ${{ github.event.inputs.action == 'destroy' }}
        run: |
          aws cloudformation delete-stack \
            --stack-name "${{ github.event.inputs.StackName }}"

          echo "Waiting for stack deletion..."

          aws cloudformation wait stack-delete-complete \
            --stack-name "${{ env.STACK_NAME }}"

          echo "CloudFormation stack deleted successfully."